version: "3"
services:
  db:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_USER: user1
      MYSQL_DATABASE: db_shopping
    ports:
      - 3306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d